### ISSUE TITLE
CA Template Request - Papermerge

### ISSUE THREAD

**Issue by TerrierX** [selfhosters/unRAID-CA-templates#133]
**Please add the dockerhub repo link and github/gitlab link below**
Docker Link: https://hub.docker.com/r/eugenci/papermerge
Github Link: https://github.com/ciur/papermerge

Docker Link Worker: https://hub.docker.com/r/eugenci/papermerge-worker
Github Link Worker: https://github.com/ciur/papermerge-worker

#### Post any additional information about the project that you know is important 
In a nutshell, Papermerge is an open source document management system (DMS) primarily designed for archiving and retrieving your digital documents. Instead of having piles of paper documents all over your desk, office or drawers - you can quickly scan them and configure your scanner to directly upload to Papermerge DMS.

Papermerge DMS on its turn will OCR the document and index it. You will be able to quickly find any (scanned!) document using full text search capabilities.

**I don't know how to create a template for that :( I am grateful for any advice**

**Comment by TerrierX** [comment]
**What I have found the following docker-compose file:** https://github.com/ciur/papermerge/blob/master/docker/docker-compose.yml

**Does it mean I need 3 containers?**
- container_name: papermerge_service
- container_name: postgres_db
- container_name: papermerge_worker

**Comment by Roxedus** [comment]
Pretty much

**Comment by TerrierX** [comment]
I tried the following but did not work any help would be appreciated:
- Postgres11 from community application
- Worker:
```
<?xml version="1.0"?>
<Container version="2">
  <Name>papermerge-worker</Name>
  <Repository>eugenci/papermerge-worker:1.2</Repository>
  <Registry>https://hub.docker.com/r/eugenci/papermerge-worker/</Registry>
  <Network>bridge</Network>
  <Support>https://hub.docker.com/r/eugenci/papermerge-worker/</Support>
  <Project/>
  <Overview>Papermerge worker - extracts (OCR) text from documents using tesseract.    Converted By Community Applications   Always verify this template (and values) against the dockerhub support page for the container</Overview>
  <Category/>
  <WebUI/>
  <TemplateURL/>
  <Icon>/plugins/dynamix.docker.manager/images/question.png</Icon>
  <Description>Papermerge worker - extracts (OCR) text from documents using tesseract.    Converted By Community Applications   Always verify this template (and values) against the dockerhub support page for the container</Description>
  <Config Name="broker_queue" Target="/opt/broker/queue" Default="/mnt/user/appdata/papermerge/broker/queue" Mode="rw" Description="Container Path: /opt/broker/queue" Type="Path" Display="always" Required="true" Mask="false">/mnt/user/appdata/papermerge/broker/queue</Config>
  <Config Name="media_root" Target="/opt/media" Default="/mnt/user/appdata/papermerge/media/" Mode="rw" Description="Container Path: /opt/media" Type="Path" Display="always" Required="true" Mask="false">/mnt/user/appdata/papermerge/media/</Config>
  <Config Name="CELERY_CONFIG_MODULE" Target="CELERY_CONFIG_MODULE" Default="config" Mode="" Description="Container Variable: CELERY_CONFIG_MODULE" Type="Variable" Display="always" Required="true" Mask="false">config</Config>
  <Config Name="C_FORCE_ROOT" Target="C_FORCE_ROOT" Default="True" Mode="" Description="Container Variable: C_FORCE_ROOT" Type="Variable" Display="always" Required="true" Mask="false">True</Config>
</Container>
```

Container does not start and no error in log

- Papermerge
```
<?xml version="1.0"?>
<Container version="2">
  <Name>Papermerge</Name>
  <Repository>eugenci/papermerge</Repository>
  <Registry>https://hub.docker.com/r/eugenci/papermerge/</Registry>
  <Network>bridge</Network>
  <Support>https://hub.docker.com/r/eugenci/papermerge/</Support>
  <Project/>
  <Overview>Open Source Document Management System for Scanned Documents   Converted By Community Applications   Always verify this template (and values) against the dockerhub support page for the container</Overview>
  <Icon>/plugins/dynamix.docker.manager/images/question.png</Icon>
  <Description>Open Source Document Management System for Scanned Documents   Converted By Community Applications   Always verify this template (and values) against the dockerhub support page for the container</Description>
  <Config Name="WebUI Port" Target="8000" Default="8000" Mode="tcp" Description="Container Port: 8000" Type="Port" Display="always" Required="true" Mask="false">8786</Config>
  <Config Name="media_root" Target="/opt/media" Default="/mnt/user/appdata/papermerge/media/" Mode="rw" Description="Container Path: /opt/media" Type="Path" Display="always" Required="true" Mask="false">/mnt/user/appdata/papermerge/media/</Config>
  <Config Name="broker_queue" Target="/opt/broker/queue" Default="/mnt/user/appdata/papermerge/broker/queue/" Mode="rw" Description="Container Path: /opt/broker/queue" Type="Path" Display="always" Required="true" Mask="false">/mnt/user/appdata/papermerge/broker/queue/</Config>
  <Config Name="POSTGRES_USER" Target="POSTGRES_USER" Default="" Mode="" Description="Container Variable: POSTGRES_USER" Type="Variable" Display="always" Required="true" Mask="false"/>
  <Config Name="POSTGRES_PASSWORD" Target="POSTGRES_PASSWORD" Default="" Mode="" Description="Container Variable: POSTGRES_PASSWORD" Type="Variable" Display="always" Required="true" Mask="false"/>
  <Config Name="POSTGRES_DB" Target="POSTGRES_DB" Default="" Mode="" Description="Container Variable: POSTGRES_DB" Type="Variable" Display="always" Required="true" Mask="false"/>
</Container>
```

Error at the start:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 220, in ensure_connection
self.connect()
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 197, in connect
self.connection = self.get_new_connection(conn_params)
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
connection = Database.connect(**conn_params)
File "/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py", line 126, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "manage.py", line 24, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 328, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 369, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 83, in wrapped
res = handle_func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 86, in handle
executor = MigrationExecutor(connection, self.migration_progress_callback)
File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 18, in __init__
self.loader = MigrationLoader(self.connection)
File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/loader.py", line 49, in __init__
self.build_graph()
File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/loader.py", line 212, in build_graph
self.applied_migrations = recorder.applied_migrations()
File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
if self.has_table():
File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/recorder.py", line 56, in has_table
return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 260, in cursor
return self._cursor()
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 236, in _cursor
self.ensure_connection()
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 220, in ensure_connection
self.connect()
File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 220, in ensure_connection
self.connect()
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 197, in connect
self.connection = self.get_new_connection(conn_params)
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
connection = Database.connect(**conn_params)
File "/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py", line 126, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known

Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 220, in ensure_connection
self.connect()
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 197, in connect
self.connection = self.get_new_connection(conn_params)
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
connection = Database.connect(**conn_params)
File "/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py", line 126, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "manage.py", line 24, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 328, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 369, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/shell.py", line 92, in handle
exec(sys.stdin.read())
File "<string>", line 6, in <module>
File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 777, in exists
return self.query.has_results(using=self.db)
File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/query.py", line 537, in has_results
return compiler.has_results()
File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1114, in has_results
return bool(self.execute_sql(SINGLE))
File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
cursor = self.connection.cursor()
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 260, in cursor
return self._cursor()
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 236, in _cursor
self.ensure_connection()
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 220, in ensure_connection
self.connect()
File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 220, in ensure_connection
self.connect()
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 197, in connect
self.connection = self.get_new_connection(conn_params)
File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
connection = Database.connect(**conn_params)
File "/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py", line 126, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known
```

I think this one is too complicated for me :(

**Comment by gilbN** [comment]
OperationalError: could not translate host name "db" to address: Name or service not known

You need to connect the container to a database. I guessing there is a variable you can add

**Comment by TerrierX** [comment]
Thank you for your response.
That is what I found and I added the variable `db` but the error did not change - no matter if I only entered the IP or IP:Port from the postgres11 container

```
version: '3.7'
services:
  app:
    image: eugenci/papermerge:1.2.1
    container_name: papermerge_service
    command: python3 /opt/papermerge/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/broker/queue
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.stage
  db:
    image: postgres:11.7
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
  worker:
    image: eugenci/papermerge-worker:1.2
    container_name: papermerge_worker
    command: bash -c "cd /opt/papermerge-worker && celery worker -A pmworker.celery -Q papermerge -l info"
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/broker/queue
    environment:
      - CELERY_CONFIG_MODULE=config
      - C_FORCE_ROOT=True
volumes:
  postgres_data:
  broker_queue:
  media_root:
```

**Comment by Roxedus** [comment]
You might have more luck with also adding `PAPERMERGE_DBPORT` as a variable if you are not using the standard port

**Comment by gilbN** [comment]
@TerrierX did you get it working with PAPERMERGE_DBPORT

**Comment by TerrierX** [comment]
@gilbN unfortunately not :(

**Comment by gilbN** [comment]
> @gilbN unfortunately not :(

Same error?

**Comment by TerrierX** [comment]
@gilbN yes

**Comment by gilbN** [comment]
Think your best bet it to run this with compose

**Comment by gilbN** [comment]
Or ask the devs on how to run this using `docker run` instead of compose. Closing this for now. Good luck!

**Comment by gilbN** [comment]
Btw, another Django app that also has hardcoded database host as `db`
 You might be able to do the same https://github.com/selfhosters/unRAID-CA-templates/issues/145#issuecomment-633479289

**Comment by TerrierX** [comment]
> Or ask the devs on how to run this using `docker run` instead of compose. Closing this for now. Good luck! 

Yes, I will do that - thank you!

**Comment by TerrierX** [comment]
> Btw, another Django app that also has hardcoded database host as `db`
>  You might be able to do the same https://github.com/selfhosters/unRAID-CA-templates/issues/145#issuecomment-633479289

I will take a look at it if I find a solution for papermerge :)
