### ISSUE TITLE
CA Template Request - <Qbitrr>

### ISSUE THREAD

**Issue by SalmonSays** [selfhosters/unRAID-CA-templates#435]
**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/feramance/qbitrr
https://github.com/Feramance/Qbitrr

#### Post any additional information about the project that you know is important 
This application hooks into qBittorrent/Sonarr/Radarr and prunes aging/stalled torrents based on customizable criteria such as time since added, then notifies Sonarr/Radarr of their removal to blacklist the release and re-search for new/better options. It's incredibly useful for long-running instances of QBT where old torrents pile up and result in a 1000+ partially downloaded backlog that takes up HDD space. 

This type of pruning does not exist (to the best of my knowledge) in Sonarr/Radarr/qBit Manage, etc natively meaning there are no current CA-available alternatives to solve this problem. Admittedly it only becomes a problem for large enough collections over a long enough time span, but I consider some level of this issue to be an inevitability that is fixed neatly by qBitrr.

**Comment by SalmonSays** [comment]
Originally on launch I received the following error on startup (which results in nearly immediate termination of the container):

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/site-packages/qBitrr/__init__.py", line 4, in <module>
    import qBitrr.logger  # noqa
  File "/usr/local/lib/python3.10/site-packages/qBitrr/logger.py", line 9, in <module>
    from qBitrr.config import (
  File "/usr/local/lib/python3.10/site-packages/qBitrr/config.py", line 11, in <module>
    from qBitrr.gen_config import MyConfig, _write_config_file, generate_doc
  File "/usr/local/lib/python3.10/site-packages/qBitrr/gen_config.py", line 12, in <module>
    from qBitrr.home_path import APPDATA_FOLDER, HOME_PATH
  File "/usr/local/lib/python3.10/site-packages/qBitrr/home_path.py", line 22, in <module>
    APPDATA_FOLDER.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/config/qBitManager'

Manually performing chmod 777 /mnt/user/appdata/qbitrr allows the program to proceed beyond this error, and generates a "config.rename_me.toml" in /mnt/user/appdata/qbitrr that needs to be renamed "config.toml". I'm not able to test it to completion tonight, but after making these changes and manually configuring the config.toml file I fully expect it to work. These additional instructions might need to be added as a note, or adding PID/GID support in the container itself to support nobody/users natively without manual intervention. Either way, config.toml will probably need manual naming to get to a working state for any future users.
